### ISSUE TITLE
Case files

### ISSUE THREAD

**Issue by Stefanomarton** [hazels-garage/bad-wings#1]
Hi there, 
love the design and functionalities of this keyboard. 
I've just bought the available kit, I would like to modify the design of the case to suit better my taste. I was wondering if it would be possible for you to make STEP file available on this repo: better print quality if directly printed and also less pain when coming to customisation, as they are easily importable in any 3D design software.

Thanks

**𝓢𝓜**

**Comment by jasonhazel** [comment]
You got it!  I've added them at `v1/cases/original`.

**Comment by Stefanomarton** [comment]
THANKS

You've just ship my order btw.

Also I understand why you don't have uploaded the pcb gerber file, but I think would be useful to have a mockup file in .STEP format, also for easy design contribution. It doesn't need to have all features and component, just for measurement and holes location.

After the keyboard kit arrive to me, if you think it is worth it I will open a PR with my case design

**Comment by jasonhazel** [comment]
I'm not against providing a step of the PCB.  I'll get one generated this evening and push it.

I'm all for a PR if you come up with something.

**Comment by jasonhazel** [comment]
PCB Step added to `v1/cases`: https://github.com/hazels-garage/bad-wings/blob/master/v1/cases/pcb.step

**Comment by Stefanomarton** [comment]
Thanks !!
